from typing import Protocol


class PortProtocol(Protocol):
    def write_data(self, value: int) -> None: ...
    def write_control(self, value: int) -> None: ...
    def read_status(self) -> int: ...
    def close(self) -> None: ...
